---
title: "LDT Section"
author: "Eric McDaniel"
date: "12/21/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r, eval=FALSE}
# load jspsych and plugin scripts
# note: this is an r code chunk

library(htmltools)
tagList(
tags$script(src='jspsych-6-2/jspsych.js'),
tags$script(src='jspsych-6-2/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='jspsychr/jspsychr.js')
)
```


```{r, results="asis}
library(jspsychr)
library(dplyr)

practice_words <- data.frame(stimulus = length(56),
                       word = rep(c("house", "potato", "impulse", "wallet", "parking",
                                    "osuhe", "tapoot", "lumspie", "lewtal", "kriganp")),
                       response = rep(c("w","p"), 1),
                       stim_type = length(56),
                       id= "ldt",
                       fontsize = "55pt")
print(practice_words)

ldtwords <- data.frame(stimulus = length(56),
                       word = rep(c("mosque", "mecca", "hijab", "imam", "arabic", 
                                    "sharia", "jihad", "infidel","terrorist", 
                                    "temple", "rabbi", "torah", "passover", "kosher", 
                                    "hebrew", "sabbath", "cheap", "shady",
                                    "cancer", "snake", "mugger", "plague", "crime", 
                                    "collision", "lava", "tobacco", "quicksand", "poison",
                                    "qusemo", "acemc", "jibah", "amim", "baraic", 
                                    "ariasah", "dihaj", "fienlid", "stritrero", "pemtle", 
                                    "bairb", "rohat", "spovaresp", "shorek", "wrebeh", 
                                    "shabatha", "pache", "syhad", "cranec", "kesan", 
                                    "grumge", "glaupe", "mirce", "slonilic", "alav", 
                                    "boctaco", "skiqudanc", "sionop")),
                       response = rep(c("w","p"), 1),
                       stim_type = length(56),
                       id= "ldt",
                       fontsize = "55pt")
print(ldtwords, n="Inf")

ldtwords$stimulus <- html_stimulus(df = ldtwords, 
                                html_content = "word",
                                html_element = "p",
                                column_names = c("fontsize"),
                                css = c("font-size"),
                                id = "id")

practice_words$stimulus <- html_stimulus(df=practice_words,
                                         html_content = "word",
                                         html_element = "p",
                                column_names = c("fontsize"),
                                css = c("font-size"),
                                id = "id")

practice_json <- stimulus_df_to_json(df = practice_words,
                                     stimulus = "stimulus",
                                     data = c("word","phase","fontsize"))

stimulus_json <- stimulus_df_to_json(df = ldtwords,
                                     stimulus = "stimulus",
                                     data = c("word"))

# write json object to script
write_to_script(practice_json,"practice_stimuli")
write_to_script(stimulus_json,"test_stimuli")
```


```{js}
/* Note this is a js (javascript) code chunk

/* experiment parameters */
var reps_per_trial_type = 1;

/*set up instructions block*/
var instructions = {
  type: "html-keyboard-response",
  stimulus: "<p>For this section of the study we would like for you to complete a word recognition task. </p>"+
  "<p> A string of letters will appear on your screen.</p>" +
  "<p>Some will be actual words, while others will be nonwords</p>"+
  "<p>If it is a word press W if it is a nonword press N</p>"+
  "<p>Respond as fast as you can, do not worry about making errors</p> +
  "<p> Between the presentation of each string of letters <b>XXXXXX</b> will appear on the screen</p> +
  "<p> To get comfortable with the task, you will begin by completing a practice round</p>"+
  "<p>Press any key to begin.</p>",
  post_trial_gap: 1000
};


/* defining practice time line */
var practice = {
  timeline: [{
    type: 'html-keyboard-response',
    choices: ["w","n"],
    trial_duration: 2000,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
    on_finish: function(data){
      var correct = false;
      if(data.response == 'w' &&  data.key_press == 82 && data.rt > -1){
        correct = true;
      } else if(data.response == 'n' &&  data.key_press == 71 && data.rt > -1){
        correct = true;
      } 
      data.correct = correct;
    },
    post_trial_gap: function() {
        return Math.floor(Math.random() * 1500) + 500;
    }
  }],
  timeline_variables: test_stimuli,
  sample: {type: 'fixed-repetitions', size: reps_per_trial_type}
};

/* setting up test */
var pre.test.instructions = {
  type: "html-keyboard-response",
  stimulus: "<p>Now that you have completed the practice, lets move to the task.</p>"+
    "<p>Remember,itIf it is a word press W if it is a nonword press N</p>"+
    "<p>Respond as fast as you can, do not worry about making errors</p> +
    "<p>Press any key to begin.</p>",
  post_trial_gap: 1000
};

/* defining test timeline */

var test = {
  timeline: [{
    type: 'html-keyboard-response',
    choices: ["w","n"],
    trial_duration: 2000,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
    on_finish: function(data){
      var correct = false;
      if(data.response == 'w' &&  data.key_press == 82 && data.rt > -1){
        correct = true;
      } else if(data.response == 'n' &&  data.key_press == 71 && data.rt > -1){
        correct = true;
      } 
      data.correct = correct;
    },
    post_trial_gap: function() {
        return Math.floor(Math.random() * 1500) + 500;
    }
  }],
  timeline_variables: test_stimuli,
  sample: {type: 'fixed-repetitions', size: reps_per_trial_type}
};

/*defining debriefing block*/
var debrief = {
  type: "html-keyboard-response",
  stimulus: function() {
    var congruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'congruent'}).select('rt').mean());
    var incongruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'incongruent'}).select('rt').mean());
    return "<p> Thank you for completing the task</p>"+
    "<p"Press any key to complete the experiment. Thank you!</p>";
  }
};

/*set up experiment structure*/
var timeline = [];
timeline.push(instructions);
timeline.push(practice);
timeline.push(pre.test.instructions);
timeline.push(test);
timeline.push(debrief);

/*start experiment*/
jsPsych.init({
    timeline: timeline,
    on_finish: function() {
        jsPsych.data.displayData();
        jspsychr.save_locally();
    }
});
```

